# Generated by Django 4.2.7 on 2025-10-24 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', help_text='Task priority level', max_length=20)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='TODO', help_text='Current task status', max_length=20)),
                ('urgency_score', models.FloatField(default=0.5, help_text='AI-calculated urgency score (0-1)')),
                ('ai_keywords', models.JSONField(blank=True, default=list, help_text='Keywords extracted by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-urgency_score', '-created_at'],
                'indexes': [models.Index(fields=['-urgency_score'], name='idx_urgency'), models.Index(fields=['priority'], name='idx_priority'), models.Index(fields=['status'], name='idx_status'), models.Index(fields=['-created_at'], name='idx_created')],
            },
        ),
    ]
